image: node:latest

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm i

variables:
  # https://stackoverflow.com/a/69746937/5083247
  NODE_OPTIONS: --openssl-legacy-provider

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

build:
  stage: build
  script:
    - pnpm run build:prod
  artifacts:
    paths:
      - dist/angular

test:
  stage: test
  script:
    - pnpx ng lint
    - pnpx prettier --check .

pages:
  stage: deploy
  script:
    - pnpm run build:gitlab
    - mv dist/angular public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
    - pages
